# Generated by Django 3.2.3 on 2021-05-16 16:24

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('LegacySite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='data',
            field=fernet_fields.fields.EncryptedTextField(),
        ),
    ]
